// Generated by dia2code
#ifndef STATE__ARMEE__H
#define STATE__ARMEE__H


namespace state {
  class Pays;
  class MobileElement;
}

#include "Pays.h"
#include "ArmeeStatus.h"
#include "MobileElement.h"

namespace state {

  /// class Armee - 
  class Armee : public state::MobileElement {
    // Associations
    state::ArmeeStatus armeeStatus;
    // Attributes
  private:
    int idJoueur;
    int nombre;
    Pays pays;
    // Operations
  public:
    Armee (int idJoueur);
    ~Armee ();
    bool isCarte ();
    void armeeRules (ArmeeStatus armeeStatus);
    TypeId const getTypeId ();
    int getIdJoueur ();
    void setIdJoueur (int idJoueur);
    int getNombre ();
    void setNombre (int nombre);
    Pays getPays ();
    void setPays (Pays pays);
    // Setters and Getters
    ArmeeStatus getArmeeStatus() const;
    void setArmeeStatus(ArmeeStatus armeeStatus);
  };

};

#endif
