// Generated by dia2code
#ifndef STATE__ARMEE__H
#define STATE__ARMEE__H

#include <string>
#include <memory>

namespace state {
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class Armee - 
  class Armee : public state::MobileElement {
    // Attributes
  private:
    int idJoueur;
    int nombre;
    std::string pays;
    // Operations
  public:
    Armee (std::string pays);
    virtual ~Armee ();
    TypeId const getTypeId ();
    virtual int getIdJoueur ();
    virtual void setIdJoueur (int idJoueur);
    virtual int getNombre ();
    virtual void setNombre (int nombre);
    virtual std::string getPays ();
    virtual std::shared_ptr<Element> clone ();
    // Setters and Getters
  };

};

#endif
