// Generated by dia2code
#ifndef STATE__ARMEESTATUS__H
#define STATE__ARMEESTATUS__H


namespace state {

  enum ArmeeStatus {
    NONDISTRIBUEE     = 1,
    DEPLOYEE     = 2,
    VAINCUE     = 3
  };

};

#endif
