// Generated by dia2code
#ifndef STATE__CARTEFORCE__H
#define STATE__CARTEFORCE__H


namespace state {

  enum CarteForce {
    NONIDENTIFIE     = 0,
    TANK     = 1,
    CANON      = 2,
    SOLDAT     = 3
  };

};

#endif
