// Generated by dia2code
#ifndef STATE__CARTE__H
#define STATE__CARTE__H


namespace state {
  class Pays;
  class MobileElement;
}

#include "Pays.h"
#include "CarteId.h"
#include "CarteForce.h"
#include "MobileElement.h"

namespace state {

  /// class Carte - 
  class Carte : public state::MobileElement {
    // Associations
    state::CarteForce carteForce;
    state::CarteId carteId;
    // Attributes
  private:
    int idJoueur;
    int const numero;
    Pays const pays;
    // Operations
  public:
    Carte (int numero , Pays pays);
    ~Carte ();
    bool const isCarte ();
    void carteRules (CarteId carteId);
    TypeId const getTypeId ();
    CarteId getCarteId ();
    CarteForce getForce ();
    int getIdJoueur ();
    void setIdJoueur (int idJoueur);
    int getNumero ();
    Pays getPays ();
    // Setters and Getters
    CarteForce getCarteForce() const;
    void setCarteForce(CarteForce carteForce);
    void setCarteId(CarteId carteId);
  };

};

#endif
