// Generated by dia2code
#ifndef STATE__CARTE__H
#define STATE__CARTE__H

#include <memory>

namespace state {
  class MobileElement;
}

#include "CarteForce.h"
#include "CarteId.h"
#include "MobileElement.h"

namespace state {

  /// class Carte - 
  class Carte : public state::MobileElement {
    // Associations
    state::CarteForce carteForce;
    state::CarteId carteId;
    // Attributes
  private:
    int idJoueur;
    int const numero;
    // Operations
  public:
    Carte (int numero, CarteForce carteForce);
    virtual ~Carte ();
    bool const isCarte ();
    TypeId const getTypeId ();
    CarteId getCarteId ();
    void setCarteId (CarteId carteId);
    CarteForce getCarteForce () const;
    int getIdJoueur ();
    void setIdJoueur (int idJoueur);
    int getNumero ();
    virtual std::unique_ptr<Element> clone ();
    // Setters and Getters
    void setCarteForce(CarteForce carteForce);
  };

};

#endif
