// Generated by dia2code
#ifndef STATE__CONTINENT__H
#define STATE__CONTINENT__H

#include <vector>

namespace state {
  class Pays;
  class StaticElement;
}

#include "Pays.h"
#include "CouleurId.h"
#include "StaticElement.h"
#include "ContinentId.h"

namespace state {

  /// class Continent - 
  class Continent : public state::StaticElement {
    // Associations
    state::ContinentId continentId;
    state::CouleurId couleurId;
    // Attributes
  private:
    std::vector<Pays> const listePays;
    // Operations
  public:
    Continent (std::vector<Pays> listePays, CouleurId couleur);
    TypeId const getTypeId ();
    ContinentId const getContinentId ();
    CouleurId const getCouleur ();
    std::vector<Pays> getListePays ();
    // Setters and Getters
    void setContinentId(ContinentId continentId);
    CouleurId getCouleurId() const;
    void setCouleurId(CouleurId couleurId);
  };

};

#endif
