// Generated by dia2code
#ifndef STATE__CONTINENTID__H
#define STATE__CONTINENTID__H


namespace state {

  enum ContinentId {
    AFRIQUE     = 1,
    ASIE     = 2,
    AMERIQUE_NORD     = 3,
    AMERIQUE_SUD     = 4,
    EUROPE     = 5,
    OCEANIE     = 6
  };

};

#endif
