// Generated by dia2code
#ifndef STATE__COULEURID__H
#define STATE__COULEURID__H


namespace state {

  enum CouleurId {
    MARRON     = 1,
    ROUGE     = 2,
    NOIR     = 3,
    JAUNE     = 4,
    VERT     = 5,
    VERT_FONCE     = 6
  };

};

#endif
