// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Position;
}

#include "Position.h"
#include "TypeId.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::TypeId typeId;
    state::Position position;
    // Operations
  public:
    Element ();
    ~Element ();
    virtual TypeId const getTypeId () = 0;
    virtual bool const isStatic () = 0;
    Position getPosition ();
    void setPosition (int x, int y);
    // Setters and Getters
    void setTypeId(TypeId typeId);
  };

};

#endif
