// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <vector>
#include <memory>

namespace state {
  class Element;
  class Position;
}

#include "Element.h"
#include "Position.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  private:
    int width;
    std::vector<std::unique_ptr<Element>> elementList;
    // Operations
  public:
    ElementTab (std::vector<std::unique_ptr<Element>> elementList);
    ~ElementTab ();
    int getWidth ();
    std::vector<std::unique_ptr<Element>> getElementList () const;
    void addElement (std::unique_ptr<Element> element);
    Position getElementPosition (std::unique_ptr<Element> element) const;
    void setElementPosition (Position position, std::unique_ptr<Element> element);
    Element* getLocatedElement (Position position) const;
    // Setters and Getters
  };

};

#endif
