// Generated by dia2code
#ifndef STATE__FENETRE__H
#define STATE__FENETRE__H

#include <stdlib.h>

namespace state {

  /// class Fenetre - 
  class Fenetre {
    // Attributes
  private:
    size_t width;
    size_t height;
    // Operations
  public:
    Fenetre (size_t width, size_t height);
    size_t  getWidth ();
    size_t getHeight ();
    void resize (size_t width, size_t height);
    // Setters and Getters
  };

};

#endif
