// Generated by dia2code
#ifndef STATE__FENETRE__H
#define STATE__FENETRE__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Fenetre - 
  class Fenetre {
    // Associations
    // Attributes
  private:
    int width;
    int height;
    // Operations
  public:
    Fenetre (int width, int height);
    int getWidth ();
    int getHeight ();
    void resize (int width, int height);
    // Setters and Getters
  };

};

#endif
