// Generated by dia2code
#ifndef STATE__PAYS__H
#define STATE__PAYS__H

#include <vector>

namespace state {
  class Pays;
  class StaticElement;
  class Continent;
}

#include "ContinentId.h"
#include "StaticElement.h"
#include "Continent.h"

namespace state {

  /// class Pays - 
  class Pays : public state::StaticElement {
    // Associations
    // Attributes
  private:
    int paysId;
    ContinentId continentId;
    std::vector<Pays> paysFrontaliers;
    // Operations
  public:
    Pays ();
    Pays (int paysId, ContinentId continentId);
    ~Pays ();
    TypeId const getTypeId ();
    int getPaysId ();
    ContinentId getContinentId ();
    std::vector<Pays> getPaysFrontaliers ();
    void setPaysFrontaliers (std::vector<Pays> paysFrontaliers);
    // Setters and Getters
  };

};

#endif
