// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    int x;
    int  y;
    // Operations
  public:
    int getX ();
    void setX (int x);
    int getY ();
    void setY (int y);
    // Setters and Getters
  };

};

#endif
