// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {
  class Position;
}


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    int x;
    int y;
    // Operations
  public:
    Position ();
    Position (int x, int y);
    int getX ();
    void setX (int x);
    int getY ();
    void setY (int y);
    friend bool operator== (Position a, Position b);
    // Setters and Getters
  };

};

#endif
