// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab armeeTab;
    ElementTab cartePiocheTab;
    ElementTab carteEnjeuTab;
    ElementTab carteDefausseTab;
    ElementTab paysTab;
    ElementTab continentTab;
    // Operations
  public:
    State ();
    virtual ~State ();
    ElementTab& getArmeeTab ();
    ElementTab& getCartePiocheTab ();
    ElementTab& getCarteEnjeuTab ();
    ElementTab& getCarteDefausseTab ();
    ElementTab& getPaysTab ();
    ElementTab& getContinentTab ();
    void setArmeeTab (ElementTab armee);
    void setCartePiocheTab (ElementTab cartePioche);
    void setCarteEnjeuTab (ElementTab carteEnjeu);
    void setCarteDefausseTab (ElementTab carteDefausse);
    void setPaysTab (ElementTab pays);
    void setContinentTab (ElementTab continent);
    // Setters and Getters
  };

};

#endif
