// Generated by dia2code
#ifndef STATE__STEPID__H
#define STATE__STEPID__H


namespace state {

  enum StepId {
    DISTRIBUTION_s     = 1,
    REPARTITION_ARMEES_s     = 2,
    CHOIX_PAYS_ATTAQUANT_s     = 3,
    CHOIX_PAYS_ATTAQUE_s     = 4,
    NB_DES_ATTAQUANT_s     = 5,
    NB_DES_ATTAQUE_s     = 6,
    DEFAUSSER_s     = 7,
    PIOCHER_s     = 8,
    ECHANGE_s     = 9,
    PLACER_NOUVELLES_ARMEES_s     = 10,
    DEPLACER_ARMEES_s     = 11
  };

};

#endif
