// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    PAYS     = 1,
    CONTINENT     = 2,
    ARMEE     = 3,
    CARTE     = 4
  };

};

#endif
