// Generated by dia2code
#ifndef RENDER__AFFICHAGE__H
#define RENDER__AFFICHAGE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace state {
  class State;
};
namespace sf {
  class Transformable;
  class Drawable;
  class Texture;
  class VertexArray;
};
namespace state {
  class ElementTab;
}

#include "state/ElementTab.h"
#include "state/State.h"

namespace render {

  /// class Affichage - 
  class Affichage : public sf::Transformable, public sf::Drawable {
    // Associations
    // Attributes
  public:
    sf::RenderWindow* window;
    // Operations
  public:
    void static AfficheMap (state::State& state, sf::RenderWindow& window);
    void static AfficheCartes (state::State& state, sf::RenderWindow& window);
    void static AfficheArmees (state::State& state, sf::RenderWindow& window);
    void draw (sf::RenderTarget& target, sf::RenderStates states);
    void static AfficheNombre (state::State& state, sf::RenderWindow& window);
    std::string static PaysClic (sf::RenderWindow& window);
    // Setters and Getters
  };

};

#endif
