// Generated by dia2code
#ifndef RENDER__ARMEETILESET__H
#define RENDER__ARMEETILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Armee;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"
#include "state/Armee.h"

namespace render {

  /// class ArmeeTileSet - 
  class ArmeeTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> armee;
    // Operations
  public:
    ArmeeTileSet ();
    ~ArmeeTileSet ();
    int const getCellWidth ();
    int const getCellHeight ();
    std::string getImageFile (const state::Armee& e) const;
    const Tile& getTile (const state::Armee& e);
    // Setters and Getters
  };

};

#endif
