// Generated by dia2code
#ifndef RENDER__CARTETILESET__H
#define RENDER__CARTETILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Carte;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"
#include "state/Carte.h"

namespace render {

  /// class CarteTileSet - 
  class CarteTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> tank;
    std::vector<Tile> soldat;
    std::vector<Tile> canon;
    // Operations
  public:
    CarteTileSet ();
    ~CarteTileSet ();
    int const getCellWidth ();
    int const getCellHeight ();
    std::string getImageFile (const state::Carte& e) const;
    const Tile& getTile (const state::Carte& e);
    // Setters and Getters
  };

};

#endif
