// Generated by dia2code
#ifndef RENDER__CONTROLLER__H
#define RENDER__CONTROLLER__H

#include <string>
#include <SFML/Graphics.hpp>

namespace state {
  class State;
}

namespace render {

  /// class Controller - 
  class Controller {
    // Attributes
  public:
    std::string pays_select;
    std::string pays_depart;
    std::string pays_arrivee;
    sf::RenderWindow* window;
    int armees_select;
    // Operations
  public:
    Controller ();
    void  Handle (state::State& state, sf::RenderWindow& window);
    void  HandleDistribution (sf::Event event );
    void  HandleChoixPays (sf::Event event , sf::RenderWindow& window);
    void HandleNbDes (sf::Event event, sf::RenderWindow& window);
     void HandleDefausser (sf::Event event );
    void  HandlePiocher (sf::Event event );
    void  HandleEchange (sf::Event event );
    void  HandlePlacerArmees (sf::Event event , sf::RenderWindow& window);
    void HandleDeplacerArmees (sf::Event event , sf::RenderWindow& window);
    // Setters and Getters
  };

};

#endif
