// Generated by dia2code
#ifndef RENDER__CONTROLLER__H
#define RENDER__CONTROLLER__H

#include <string>
#include <SFML/Graphics.hpp>

namespace state {
  class State;
}

namespace render {

  /// class Controller - 
  class Controller {
    // Attributes
  public:
    std::string pays_select;
    std::string pays_depart;
    std::string pays_arrivee;
    sf::RenderWindow* window;
    int armees_select;
    // Operations
  public:
    Controller ();
    void  Handle (state::State& state, sf::RenderWindow& window);
    void HandlePasser (state::State& state, sf::Event event);
    void HandleFin (state::State& state, sf::Event event);
    void  HandleDistribution (state::State& state, sf::Event event );
    void  HandleChoixPaysAttaquant (state::State& state, sf::Event event , sf::RenderWindow& window);
    void  HandleChoixPaysAttaque (state::State& state, sf::Event event , sf::RenderWindow& window);
    void HandleNbDesAttaquant (state::State& state, sf::Event event, sf::RenderWindow& window);
    void HandleNbDesAttaque (state::State& state, sf::Event event, sf::RenderWindow& window);
     void HandleDefausser (state::State& state, sf::Event event );
    void  HandlePiocher (state::State& state, sf::Event event );
    void  HandleEchange (state::State& state, sf::Event event );
    void  HandlePlacerArmees (state::State& state, sf::Event event , sf::RenderWindow& window);
    void HandleDeplacerArmees (state::State& state, sf::Event event , sf::RenderWindow& window);
    void HandleUndo (state::State& state, sf::Event event);
    // Setters and Getters
  };

};

#endif
