// Generated by dia2code
#ifndef RENDER__ELEMENTTABLAYER__H
#define RENDER__ELEMENTTABLAYER__H


namespace state {
  class ElementTab;
}

#include "state/ElementTab.h"

namespace render {

  /// class ElementTabLayer - 
  class ElementTabLayer {
    // Associations
    // Attributes
  private:
    const state::ElementTab& tab;
    // Operations
  public:
    ElementTabLayer (const state::ElementTab& tab );
    void initSurface ();
    // Setters and Getters
  };

};

#endif
