// Generated by dia2code
#ifndef RENDER__MAPTILESET__H
#define RENDER__MAPTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class MapTileSet - 
  class MapTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> map;
    // Operations
  public:
    MapTileSet ();
    ~MapTileSet ();
    int const getCellWidth ();
    int const getCellHeight ();
    std::string getImageFile (const state::Element& e) const;
    const Tile& getTile (char c) const;
    // Setters and Getters
  };

};

#endif
