// Generated by dia2code
#ifndef RENDER__STATELAYER__H
#define RENDER__STATELAYER__H

#include <stdlib.h>

namespace state {
  class State;
};
namespace render {
  class Layer;
}

#include "Layer.h"
#include "state/State.h"

namespace render {

  /// class StateLayer - 
  class StateLayer : public render::Layer {
    // Associations
    // Attributes
  private:
    const state::State& state;
    const size_t gumCountMinIdx     = 0;
    const size_t  gumCountMaxIdx     = 2;
    // Operations
  public:
    StateLayer (const state::State& state);
    void initSurface ();
    // Setters and Getters
  };

};

#endif
