// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  public:
    int height     = 16;
  protected:
    int x     = 0;
    /// 													
    int y     = 0;
    int width     = 16;
    // Operations
  public:
    Tile ();
    Tile (int x, int y, int w, int h);
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    int getWidth() const;
    void setWidth(int width);
  };

};

#endif
