// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
}

#include "state/Element.h"
#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    virtual ~TileSet ();
    virtual int const getCellWidth () = 0;
    virtual int const getCellHeight () = 0;
    virtual const std::string getImageFile () const = 0;
    const Tile& getTile (const state::Element& e) const;
    // Setters and Getters
  };

};

#endif
