// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/State.h"
#include "engine/Command.h"

namespace ai {

  /// class AI - 
  class AI {
    // Operations
  public:
    virtual static void aiDistribution (state::State state, int nbJoueurs = 3) = 0;
    virtual static bool aiRepartitionArmees (int idJoueur, state::State state) = 0;
    virtual static std::string aiChoixPaysAttaquant () = 0;
    virtual static std::string aiChoixPaysAttaque () = 0;
    virtual static int aiNbDesLancers () = 0;
    virtual static int aiEchange (int idJoueur, state::State state) = 0;
    virtual static void aiPlacerNouvellesArmees (int idJoueur, int nouvellesArmees, state::State state) = 0;
    virtual static void aiDeplacerArmees (int idJoueur, state::State state) = 0;
    // Setters and Getters
  };

};

#endif
