// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace state {
  class State;
};
namespace engine {
  class Commande;
  class CommandeComposite;
  class TourDeJeu;
  class DeplacerArmees;
  class EchangeCartes;
  class Defausser;
  class IssueDuCombat;
  class DesAttaque;
  class DesAttaquant;
  class ChoixPaysAttaque;
  class ChoixPaysAttaquant;
  class PlacementArmees;
};
namespace state {
  class Carte;
};
namespace engine {
  class FinTour;
  class Undo;
  class Piocher;
  class Passer;
  class Distribution;
}

#include "engine/CommandeComposite.h"
#include "engine/TourDeJeu.h"
#include "engine/DeplacerArmees.h"
#include "engine/EchangeCartes.h"
#include "engine/Defausser.h"
#include "engine/IssueDuCombat.h"
#include "engine/DesAttaque.h"
#include "engine/DesAttaquant.h"
#include "engine/ChoixPaysAttaque.h"
#include "engine/ChoixPaysAttaquant.h"
#include "engine/PlacementArmees.h"
#include "state/Carte.h"
#include "engine/FinTour.h"
#include "engine/Undo.h"
#include "engine/Piocher.h"
#include "engine/Passer.h"
#include "engine/Distribution.h"
#include "engine/Commande.h"
#include "state/State.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    int idJoueurAI;
    // Operations
  public:
    AI (int idJoueurAI);
    int getIdJoueurAI ();
    void aiRemplirCommandes (state::State* state);
    virtual engine::Commande* aiRepartitionArmees (state::State& state) = 0;
    virtual engine::Commande* aiChoixPaysAttaquant (state::State& state) = 0;
    virtual engine::Commande* aiChoixPaysAttaque (state::State& state) = 0;
    virtual engine::Commande* aiDesAttaquant (state::State& state) = 0;
    virtual engine::Commande* aiDesAttaque (state::State& state) = 0;
    virtual engine::Commande* aiDefausser (state::State& state) = 0;
    virtual engine::Commande* aiEchange (state::State& state) = 0;
    virtual engine::Commande* aiPlacementArmees (state::State& state) = 0;
    virtual engine::Commande* aiDeplacerArmees (state::State& state) = 0;
    // Setters and Getters
    void setIdJoueurAI(int idJoueurAI);
  };

};

#endif
