// Generated by dia2code
#ifndef AI__DEEPAI__H
#define AI__DEEPAI__H

#include <string>

namespace state {
  class State;
};
namespace ai {
  class AI;
  class HeuristicAI;
}

#include "AI.h"
#include "HeuristicAI.h"

namespace ai {

  /// class DeepAI - 
  class DeepAI : public ai::AI {
    // Associations
    // Attributes
  public:
    std::string paysAttaquant1;
    std::string paysAttaquant2;
    std::string paysAttaque1;
    std::string paysAttaque2;
    // Operations
  public:
    DeepAI (int idJoueur);
    int evalState (state::State& state, int profondeur, int minMax);
    void aiRepartitionArmees (state::State& state);
    void aiChoixPaysAttaquant (state::State& state);
    void aiChoixPaysAttaque (state::State& state);
    void aiDesAttaquant (state::State& state);
    void aiDesAttaque (state::State& state);
    void aiDefausser (state::State& state);
    void aiEchange (state::State& state);
    void aiPlacementArmees (state::State& state);
    void aiDeplacerArmees (state::State& state);
    void initializeEtatsPossibles (state::State& state);
    // Setters and Getters
  };

};

#endif
