// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <string>
#include <vector>

namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "state/State.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Operations
  public:
    void aiPlacementArmees (state::State state);
    void aiChoixPaysAttaquant (std::vector<std::string> blackList, state::State state);
    void aiChoixPaysAttaque (state::State state);
    void aiDesAttaquant (state::State state);
    void aiDesAttaque (state::State state);
    void aiDefausser (state::State state);
    void aiEchange (state::State state);
    void aiDeplacerArmees (state::State state);
    // Setters and Getters
  };

};

#endif
