// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <string>
#include <vector>

namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "state/State.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Operations
  public:
    void aiRepartitionArmees (int idJoueur, state::State state);
    std::string aiChoixPaysAttaquant (int idJoueur, std::vector<std::string> blackList, state::State state);
    std::string aiChoixPaysAttaque (int idJoueur, std::string paysAttaquant, state::State state);
    int aiNbDesLancersAttaques (std::string paysAttaquant, std::string paysAttaque, state::State state);
    int aiNbDesLancersDefenses (std::string paysAttaque, state::State state);
    void aiGainCartes (int idJoueur, int victoire, state::State state);
    int aiEchange (int idJoueur, state::State state);
    void aiPlacerNouvellesArmees (int idJoueur, int nouvellesArmees, state::State state);
    void aiDeplacerArmees (int idJoueur, state::State state);
    void aiJouer (int numeroTour, int idJoueur, state::State state);
    // Setters and Getters
  };

};

#endif
