// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H


namespace engine {
  class Commande;
};
namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Operations
  public:
    RandomAI (int idJoueur);
    engine::Commande* aiRepartitionArmees (state::State& state);
    engine::Commande* aiChoixPaysAttaquant (state::State& state);
    engine::Commande* aiChoixPaysAttaque (state::State& state);
    engine::Commande* aiDesAttaquant (state::State& state);
    engine::Commande* aiDesAttaque (state::State& state);
    engine::Commande* aiDefausser (state::State& state);
    engine::Commande* aiEchange (state::State& state);
    engine::Commande* aiPlacementArmees (state::State& state);
    engine::Commande* aiDeplacerArmees (state::State& state);
    // Setters and Getters
  };

};

#endif
