// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <string>

namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "state/State.h"
#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Operations
  public:
    virtual static void aiDistribution (state::State state, int nbJoueurs = 3);
    virtual static bool aiRepartitionArmees (int idJoueur, state::State state);
    virtual static std::string aiChoixPaysAttaquant ();
    virtual static std::string aiChoixPaysAttaque ();
    virtual static int aiNbDesLancers ();
    virtual static int aiEchange (int idJoueur, state::State state);
    virtual static void aiPlacerNouvellesArmees (int idJoueur, int nouvellesArmees, state::State state);
    virtual static void aiDeplacerArmees (int idJoueur, state::State state);
    // Setters and Getters
  };

};

#endif
