// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <string>

namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "state/State.h"
#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Operations
  public:
    RandomAI ();
    ~RandomAI ();
    bool aiRepartitionArmees (int idJoueur, state::State state);
    std::string aiChoixPaysAttaquant (int idJoueur, state::State state);
    std::string aiChoixPaysAttaque (int idJoueur, std::string paysAttaquant, state::State state);
    int aiNbDesLancersAttaques ();
    int aiNbDesLancersDefenses ();
    void aiGainCartes (int idJoueur, bool victoire, state::State state);
    int aiEchange (int idJoueur, state::State state);
    void aiPlacerNouvellesArmees (int idJoueur, int nouvellesArmees, state::State state);
    void aiDeplacerArmees (int idJoueur, state::State state);
    void aiJouer (int numeroTour, int idJoueur, state::State state);
    // Setters and Getters
  };

};

#endif
