// Generated by dia2code
#ifndef ENGINE__ATTRIBUTIONTERRITOIRES__H
#define ENGINE__ATTRIBUTIONTERRITOIRES__H


namespace state {
  class State;
};
namespace engine {
  class Commande;
  class PlacementArmees;
}

#include "state/State.h"
#include "Commande.h"
#include "PlacementArmees.h"

namespace engine {

  /// class AttributionTerritoires - 
  class AttributionTerritoires : public engine::Commande {
    // Associations
    // Operations
  public:
    virtual ~AttributionTerritoires ();
    IdCommande const getIdCommande ();
    static void distribution (state::State state, int nbJoueurs = 3);
    static bool repartitionArmees (int idJoueur, state::State state);
    static void undoRepartitionArmees (int idJoueur, state::State state);
    // Setters and Getters
  };

};

#endif
