// Generated by dia2code
#ifndef ENGINE__CHOIXPAYSATTAQUE__H
#define ENGINE__CHOIXPAYSATTAQUE__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class ChoixPays;
}

#include "state/State.h"
#include "ChoixPays.h"

namespace engine {

  /// class ChoixPaysAttaque - 
  class ChoixPaysAttaque : public engine::ChoixPays {
    // Operations
  public:
    ChoixPaysAttaque (std::string pays);
    virtual ~ChoixPaysAttaque ();
    static bool estFrontalier (std::string pays1, std::string pays2, state::State state);
    bool verif (state::State state);
    void exec (state::State state);
    void undo (state::State state);
    // Setters and Getters
  };

};

#endif
