// Generated by dia2code
#ifndef ENGINE__CHOIXPAYS__H
#define ENGINE__CHOIXPAYS__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "state/State.h"
#include "Commande.h"

namespace engine {

  /// class ChoixPays - 
  class ChoixPays : public engine::Commande {
    // Operations
  public:
    virtual ~ChoixPays ();
    IdCommande const getIdCommande ();
    static std::string choixPaysAttaquant ();
    static bool verifPaysAttaquant (int idJoueur, std::string paysAttaquant, state::State state);
    static std::string choixPaysAttaque ();
    static bool verifPaysAttaque (int idJoueur, std::string paysAttaque, std::string paysAttaquant, state::State state);
    // Setters and Getters
  };

};

#endif
