// Generated by dia2code
#ifndef ENGINE__CHOIXPAYS__H
#define ENGINE__CHOIXPAYS__H


namespace engine {
  class Commande;
};
namespace state {
  class Pays;
}

#include "Commande.h"
#include "state/Pays.h"

namespace engine {

  /// class ChoixPays - 
  class ChoixPays : public engine::Commande {
    // Operations
  public:
    virtual ~ChoixPays ();
    IdCommande const getIdCommande ();
    static state::Pays paysAttaquant ();
    static bool verifPaysAttaquant ();
    static state::Pays paysAttaque ();
    static bool verifPaysAttaquant ();
    // Setters and Getters
  };

};

#endif
