// Generated by dia2code
#ifndef ENGINE__CHOIXPAYSATTAQUANT__H
#define ENGINE__CHOIXPAYSATTAQUANT__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class ChoixPays;
}

#include "ChoixPays.h"

namespace engine {

  /// class ChoixPaysAttaquant - 
  class ChoixPaysAttaquant : public engine::ChoixPays {
    // Operations
  public:
    ChoixPaysAttaquant (int idJoueur, std::string pays);
    virtual ~ChoixPaysAttaquant ();
    IdCommande const getIdCommande ();
    std::string getPays ();
    bool verif (state::State& state);
    void exec (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
