// Generated by dia2code
#ifndef ENGINE__COMBAT__H
#define ENGINE__COMBAT__H

#include <string>
#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Commande;
};
namespace state {
  class Element;
  class Armee;
}

#include "state/State.h"
#include "Commande.h"
#include "state/Element.h"
#include "state/Armee.h"

namespace engine {

  /// class Combat - 
  class Combat : public engine::Commande {
    // Operations
  public:
    virtual ~Combat ();
    IdCommande const getIdCommande ();
    static int nbDesLances ();
    static bool verifNbAttaques (int nbDes, std::string paysAttaquant, state::State state);
    static bool verifNbDefenses (int nbDes, std::string paysAttaque, state::State state);
    static std::vector<int> lancerDes (int nbDes);
    // Setters and Getters
  };

};

#endif
