// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H


namespace state {
  class ElementTab;
  class State;
}

#include "state/ElementTab.h"
#include "state/State.h"
#include "IdCommande.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Associations
    engine::IdCommande idCommande;
    // Operations
  public:
    virtual ~Commande ();
    virtual IdCommande const getIdCommande () = 0;
    // Setters and Getters
    void setIdCommande(IdCommande idCommande);
  };

};

#endif
