// Generated by dia2code
#ifndef ENGINE__COMMANDE__H
#define ENGINE__COMMANDE__H

#include <string>

namespace state {
  class State;
  class ElementTab;
}

#include "state/ElementTab.h"
#include "state/State.h"
#include "IdCommande.h"

namespace engine {

  /// class Commande - 
  class Commande {
    // Associations
    engine::IdCommande idCommande;
    // Operations
  public:
    Commande ();
    virtual ~Commande ();
    virtual IdCommande const getIdCommande ();
    virtual bool verif (state::State& state);
    virtual void exec (state::State& state);
    virtual void undo (state::State& state);
    virtual int getNumeroCarte ();
    virtual int getNbArmees ();
    virtual void setNbArmees (int nbArmees);
    virtual std::string getPays ();
    virtual int getNbDes ();
    // Setters and Getters
    void setIdCommande(IdCommande idCommande);
  };

};

#endif
