// Generated by dia2code
#ifndef ENGINE__CREATIONMOBILEELEMENTS__H
#define ENGINE__CREATIONMOBILEELEMENTS__H

#include <vector>
#include <string>
#include <map>

namespace engine {
  class Commande;
};
namespace state {
  class Armee;
  class Carte;
}

#include "Commande.h"
#include "state/Armee.h"
#include "state/Carte.h"

namespace engine {

  /// class CreationMobileElements - 
  class CreationMobileElements : public engine::Commande {
    // Operations
  public:
    virtual ~CreationMobileElements ();
    IdCommande const getIdCommande ();
    static std::vector<state::Carte> creationPioche ();
    static std::vector<state::Carte> creationEnJeu ();
    static std::vector<state::Carte> creationDefausse ();
    static std::map<std::string, state::Armee> creationArmees ();
    // Setters and Getters
  };

};

#endif
