// Generated by dia2code
#ifndef ENGINE__CREATIONSTATICELEMENTS__H
#define ENGINE__CREATIONSTATICELEMENTS__H

#include <string>
#include <map>

namespace engine {
  class Commande;
};
namespace state {
  class Continent;
  class Pays;
}

#include "Commande.h"
#include "state/Continent.h"
#include "state/Pays.h"

namespace engine {

  /// class CreationStaticElements - 
  class CreationStaticElements : public engine::Commande {
    // Operations
  public:
    virtual ~CreationStaticElements ();
    IdCommande const getIdCommande ();
    static std::map<std::string, state::Pays> creationPays ();
    static state::Continent creationAfrique (std::map<std::string, state::Pays> mapPays);
    static state::Continent creationAsie (std::map<std::string, state::Pays> mapPays);
    static state::Continent creationAmeriqueNord (std::map<std::string, state::Pays> mapPays);
    static state::Continent creationAmeriqueSud (std::map<std::string, state::Pays> mapPays);
    static state::Continent creationEurope (std::map<std::string, state::Pays> mapPays);
    static state::Continent creationOceanie (std::map<std::string, state::Pays> mapPays);
    // Setters and Getters
  };

};

#endif
