// Generated by dia2code
#ifndef ENGINE__DEFAUSSER__H
#define ENGINE__DEFAUSSER__H


namespace state {
  class State;
};
namespace engine {
  class Cartes;
}

#include "state/State.h"
#include "Cartes.h"

namespace engine {

  /// class Defausser - 
  class Defausser : public engine::Cartes {
    // Operations
  public:
    Defausser (int numeroCarte);
    virtual ~Defausser ();
    IdCommande const getIdCommande ();
    void exec (state::State state);
    void undo (state::State state);
    // Setters and Getters
  };

};

#endif
