// Generated by dia2code
#ifndef ENGINE__DESATTAQUE__H
#define ENGINE__DESATTAQUE__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Des;
}

#include "Des.h"

namespace engine {

  /// class DesAttaque - 
  class DesAttaque : public engine::Des {
    // Attributes
  private:
    std::vector<int> desBleus;
    // Operations
  public:
    DesAttaque (int nbDes);
    DesAttaque (int nbDes, std::vector<int> desBleus);
    virtual ~DesAttaque ();
    bool verif (state::State& state);
    void exec (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
