// Generated by dia2code
#ifndef ENGINE__ECHANGECARTES__H
#define ENGINE__ECHANGECARTES__H


namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "state/State.h"
#include "Commande.h"

namespace engine {

  /// class EchangeCartes - 
  class EchangeCartes : public engine::Commande {
    // Operations
  public:
    virtual ~EchangeCartes ();
    IdCommande const getIdCommande ();
    static int echange (state::State state);
    // Setters and Getters
  };

};

#endif
