// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Setters and Getters
  };

};

#endif
