// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H


namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "state/State.h"
#include "Commande.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    state::State currentState;
  protected:
    bool arretJeu     = false;
    // Operations
  public:
    Engine ();
    ~Engine ();
    state::State getCurrentState ();
    void setArretJeu (bool arretJeu);
    // Setters and Getters
    bool getArretJeu() const;
  };

};

#endif
