// Generated by dia2code
#ifndef ENGINE__GAINCOMBAT__H
#define ENGINE__GAINCOMBAT__H


namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class GainCombat - 
  class GainCombat : public engine::Commande {
    // Operations
  public:
    virtual ~GainCombat ();
    IdCommande const getIdCommande ();
    static void gainCartes ();
    static int gainArmees ();
    // Setters and Getters
  };

};

#endif
