// Generated by dia2code
#ifndef ENGINE__GESTIONCARTES__H
#define ENGINE__GESTIONCARTES__H

#include <memory>

namespace state {
  class State;
  class Carte;
};
namespace engine {
  class Commande;
}

#include "state/State.h"
#include "state/Carte.h"
#include "Commande.h"

namespace engine {

  /// class GestionCartes - 
  class GestionCartes : public engine::Commande {
    // Operations
  public:
    virtual ~GestionCartes ();
    IdCommande const getIdCommande ();
    static std::shared_ptr<state::Carte> piocher (state::State state);
    static void defausser (std::shared_ptr<state::Carte> carteDefausse, state::State state);
    // Setters and Getters
  };

};

#endif
