// Generated by dia2code
#ifndef ENGINE__GESTIONCARTES__H
#define ENGINE__GESTIONCARTES__H


namespace engine {
  class Commande;
};
namespace state {
  class Carte;
}

#include "Commande.h"
#include "state/Carte.h"

namespace engine {

  /// class GestionCartes - 
  class GestionCartes : public engine::Commande {
    // Operations
  public:
    virtual ~GestionCartes ();
    IdCommande const getIdCommande ();
    static state::Carte piocher ();
    static void defausser ();
    // Setters and Getters
  };

};

#endif
