// Generated by dia2code
#ifndef ENGINE__GESTIONCARTES__H
#define ENGINE__GESTIONCARTES__H


namespace state {
  class State;
};
namespace engine {
  class Commande;
};
namespace state {
  class Carte;
}

#include "state/State.h"
#include "Commande.h"
#include "state/Carte.h"

namespace engine {

  /// class GestionCartes - 
  class GestionCartes : public engine::Commande {
    // Operations
  public:
    virtual ~GestionCartes ();
    IdCommande const getIdCommande ();
    static void piocher (int idJoueur, state::State state);
    static void defausser (int numeroCarteDefausse, state::State state);
    static void undoPiocher (state::State state);
    static void undoDefausser (int idJoueur, state::State state);
    // Setters and Getters
  };

};

#endif
