// Generated by dia2code
#ifndef ENGINE__IDCOMMANDE__H
#define ENGINE__IDCOMMANDE__H


namespace engine {

  enum IdCommande {
    COMMANDE_c     = 0,
    DISTRIBUTION_c     = 1,
    CHOIX_PAYS_ATTAQUANT_c     = 3,
    CHOIX_PAYS_ATTAQUE_c     = 4,
    NB_DES_ATTAQUANT_c     = 5,
    NB_DES_ATTAQUE_c     = 6,
    DEFAUSSER_c     = 7,
    PIOCHER_c     = 8,
    ECHANGE_c     = 9,
    PLACER_ARMEES_c     = 10,
    DEPLACER_ARMEES_c     = 11,
    PASSER_c     = 12,
    UNDO_c     = 13
  };

};

#endif
