// Generated by dia2code
#ifndef ENGINE__IDCOMMANDE__H
#define ENGINE__IDCOMMANDE__H


namespace engine {

  enum IdCommande {
    CREASTATIC     = 1,
    CREAMOBILE     = 2,
    ATTRIBUTERR     = 3,
    GESTCARTES     = 4,
    CHOIXPAYS     = 5,
    COMBAT     = 6,
    ISSUECOMBAT     = 7,
    GAINCOMBAT     = 8,
    ECHANGECARTES     = 9,
    PLACEARMEES     = 10
  };

};

#endif
