// Generated by dia2code
#ifndef ENGINE__ISSUEDUCOMBAT__H
#define ENGINE__ISSUEDUCOMBAT__H

#include <vector>
#include <string>

namespace state {
  class State;
};
namespace engine {
  class Commande;
}

#include "state/State.h"
#include "Commande.h"

namespace engine {

  /// class IssueDuCombat - 
  class IssueDuCombat : public engine::Commande {
    // Operations
  public:
    virtual ~IssueDuCombat ();
    IdCommande const getIdCommande ();
    static int victoire (std::vector<int>& desRouges, std::vector<int>& desBleus, std::string paysAttaquant, std::string paysAttaque, state::State state);
    static void undoVictoire (int victoire, std::vector<int>& desRouges, std::vector<int>& desBleus, std::string paysAttaquant, std::string paysAttaque, state::State state);
    // Setters and Getters
  };

};

#endif
