// Generated by dia2code
#ifndef ENGINE__ISSUEDUCOMBAT__H
#define ENGINE__ISSUEDUCOMBAT__H


namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class IssueDuCombat - 
  class IssueDuCombat : public engine::Commande {
    // Operations
  public:
    virtual ~IssueDuCombat ();
    IdCommande const getIdCommande ();
    static void comparaison ();
    static void victoire ();
    // Setters and Getters
  };

};

#endif
