// Generated by dia2code
#ifndef ENGINE__PASSER__H
#define ENGINE__PASSER__H


namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class Passer - 
  class Passer : public engine::Commande {
    // Attributes
  private:
    /// 	
    bool fin;
    // Operations
  public:
    Passer (int idJoueurCommande, bool fin);
    virtual ~Passer ();
    IdCommande const getIdCommande ();
    bool getFin ();
    // Setters and Getters
  };

};

#endif
