// Generated by dia2code
#ifndef ENGINE__PASSER__H
#define ENGINE__PASSER__H


namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class Passer - 
  class Passer : public engine::Commande {
    // Operations
  public:
    virtual ~Passer ();
    IdCommande const getIdCommande ();
    // Setters and Getters
  };

};

#endif
