// Generated by dia2code
#ifndef ENGINE__PIOCHER__H
#define ENGINE__PIOCHER__H


namespace state {
  class State;
};
namespace engine {
  class Cartes;
};
namespace state {
  class Carte;
}

#include "Cartes.h"
#include "state/Carte.h"

namespace engine {

  /// class Piocher - 
  class Piocher : public engine::Cartes {
    // Operations
  public:
    Piocher ();
    Piocher (int idJoueur, int numeroCarte);
    virtual ~Piocher ();
    IdCommande const getIdCommande ();
    void exec (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
