// Generated by dia2code
#ifndef ENGINE__PIOCHER__H
#define ENGINE__PIOCHER__H


namespace state {
  class State;
};
namespace engine {
  class Cartes;
}

#include "Cartes.h"

namespace engine {

  /// class Piocher - 
  class Piocher : public engine::Cartes {
    // Operations
  public:
    Piocher (int idJoueurCommande);
    virtual ~Piocher ();
    IdCommande const getIdCommande ();
    void writeToJson ();
    void exec (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
