// Generated by dia2code
#ifndef ENGINE__PLACEMENTARMEES__H
#define ENGINE__PLACEMENTARMEES__H

#include <SFML/Graphics.hpp>

namespace state {
  class State;
};
namespace engine {
  class Commande;
  class ChoixPays;
}

#include "state/State.h"
#include "Commande.h"
#include "ChoixPays.h"

namespace engine {

  /// class PlacementArmees - 
  class PlacementArmees : public engine::Commande {
    // Associations
    // Operations
  public:
    virtual ~PlacementArmees ();
    IdCommande const getIdCommande ();
    static void placerNouvellesArmees (int idJoueur, int nouvellesArmees, state::State state, sf::RenderWindow& window, sf::Event event);
    static void deplacerArmees (int idJoueur, state::State state);
    // Setters and Getters
  };

};

#endif
