// Generated by dia2code
#ifndef ENGINE__PLACEMENTARMEES__H
#define ENGINE__PLACEMENTARMEES__H


namespace engine {
  class Commande;
}

#include "Commande.h"

namespace engine {

  /// class PlacementArmees - 
  class PlacementArmees : public engine::Commande {
    // Operations
  public:
    virtual ~PlacementArmees ();
    IdCommande const getIdCommande ();
    static void placerNouvellesArmees (int nouvellesArmees);
    static void deplacerArmees ();
    // Setters and Getters
  };

};

#endif
