// Generated by dia2code
#ifndef ENGINE__TOURDEJEU__H
#define ENGINE__TOURDEJEU__H


namespace state {
  class State;
};
namespace engine {
  class PlacementArmees;
  class AttributionTerritoires;
  class ChoixPays;
  class EchangeCartes;
  class GainCombat;
  class IssueDuCombat;
  class Combat;
}

#include "state/State.h"
#include "PlacementArmees.h"
#include "AttributionTerritoires.h"
#include "ChoixPays.h"
#include "EchangeCartes.h"
#include "GainCombat.h"
#include "IssueDuCombat.h"
#include "Combat.h"

namespace engine {

  /// class TourDeJeu - 
  class TourDeJeu {
    // Associations
    // Operations
  public:
    static void jouer (int numeroTour, int idJoueur, state::State currentState);
    // Setters and Getters
  };

};

#endif
