// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H


namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    string name;
    int type;
    // Operations
  public:
    User (string name, int type);
    // Setters and Getters
  };

};

#endif
