// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H

#include <memory>

namespace ai {
  class AI;
};
namespace render {
  class Controller;
  class Affichage;
}

#include "ai/AI.h"
#include "render/Controller.h"
#include "render/Affichage.h"

namespace client {

  /// class Client - 
  class Client : public render::Controller {
    // Associations
    // Attributes
  private:
    std::unique_ptr<ai::AI> characters_ai;
    state::State state;
    // Operations
  public:
    Client ();
    void run ();
    void connect  ();
    // Setters and Getters
  };

};

#endif
